apiVersion: v1
kind: Namespace
metadata:
  name: ragflow
---
# ==============================
# ConfigMaps for configurations
# ==============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: ragflow-config
  namespace: ragflow
data:
  # From .env file (non-sensitive configs)
  DOC_ENGINE: "elasticsearch"
  STACK_VERSION: "8.11.3"
  ES_PORT: "1200"
  OS_PORT: "1201"
  MEM_LIMIT: "8073741824"
  INFINITY_THRIFT_PORT: "23817"
  INFINITY_HTTP_PORT: "23820"
  INFINITY_PSQL_PORT: "5432"
  MYSQL_DBNAME: "rag_flow"
  MYSQL_PORT: "5455"
  MINIO_CONSOLE_PORT: "9001"
  MINIO_PORT: "9000"
  REDIS_PORT: "6379"
  SVR_HTTP_PORT: "9380"
  TIMEZONE: "Asia/Shanghai"
  REGISTER_ENABLED: "1"
  # Infinity configuration
  infinity_conf.toml: |
    [general]
    version                  = "0.6.0"
    time_zone                = "utc-8"
    
    [network]
    server_address           = "0.0.0.0"
    postgres_port            = 5432
    http_port                = 23820
    client_port              = 23817
    connection_pool_size     = 128
    
    [log]
    log_filename             = "infinity.log"
    log_dir                  = "/var/infinity/log"
    log_to_stdout            = true
    log_file_max_size        = "100MB"
    log_file_rotate_count    = 10
    log_level                = "info"
    
    [storage]
    persistence_dir         = "/var/infinity/persistence"
    data_dir                = "/var/infinity/data"
    optimize_interval        = "10s"
    cleanup_interval         = "60s"
    compact_interval         = "120s"
    storage_type             = "local"
    mem_index_capacity       = 65536
    
    [buffer]
    buffer_manager_size      = "8GB"
    lru_num                  = 7
    temp_dir                 = "/var/infinity/tmp"
    result_cache             = "off"
    memindex_memory_quota    = "4GB"
    
    [wal]
    wal_dir                       = "/var/infinity/wal"
    full_checkpoint_interval      = "30s"
    delta_checkpoint_interval     = "5s"
    wal_compact_threshold         = "1GB"
    wal_flush                     = "only_write"
    
    [resource]
    resource_dir                  = "/var/infinity/resource"
  # MySQL init script
  init.sql: |
    CREATE DATABASE IF NOT EXISTS rag_flow;
    USE rag_flow;
---
# ======================
# Secrets for credentials
# ======================
apiVersion: v1
kind: Secret
metadata:
  name: ragflow-secrets
  namespace: ragflow
type: Opaque
stringData:
  ELASTIC_PASSWORD: "infini_rag_flow"
  OPENSEARCH_PASSWORD: "infini_rag_flow_OS_01"
  MYSQL_PASSWORD: "infini_rag_flow"
  MINIO_USER: "rag_flow"
  MINIO_PASSWORD: "infini_rag_flow"
  REDIS_PASSWORD: "infini_rag_flow"
  KIBANA_PASSWORD: "infini_rag_flow"
---
# ==============================
# Persistent Volume Claims (PVCs)
# ==============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata01
  namespace: ragflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osdata01
  namespace: ragflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infinity-data
  namespace: ragflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: ragflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: ragflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: ragflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ======================
# Elasticsearch Service
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es01
  namespace: ragflow
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.11.3
        env:
        - name: node.name
          value: "es01"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ragflow-secrets
              key: ELASTIC_PASSWORD
        - name: bootstrap.memory_lock
          value: "false"
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: xpack.security.transport.ssl.enabled
          value: "false"
        - name: cluster.routing.allocation.disk.watermark.low
          value: "5gb"
        - name: cluster.routing.allocation.disk.watermark.high
          value: "3gb"
        - name: cluster.routing.allocation.disk.watermark.flood_stage
          value: "2gb"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        ports:
        - containerPort: 9200
        resources:
          limits:
            memory: 8Gi
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
        readinessProbe:
          exec:
            command:
            - curl
            - http://localhost:9200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: esdata
        persistentVolumeClaim:
          claimName: esdata01
---
apiVersion: v1
kind: Service
metadata:
  name: es01
  namespace: ragflow
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 31200
  type: NodePort
---
# ======================
# OpenSearch Service
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch01
  namespace: ragflow
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: hub.icert.top/opensearchproject/opensearch:2.19.1
        env:
        - name: node.name
          value: "opensearch01"
        - name: OPENSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ragflow-secrets
              key: OPENSEARCH_PASSWORD
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ragflow-secrets
              key: OPENSEARCH_PASSWORD
        - name: bootstrap.memory_lock
          value: "false"
        - name: discovery.type
          value: "single-node"
        - name: plugins.security.disabled
          value: "false"
        - name: plugins.security.ssl.http.enabled
          value: "false"
        - name: plugins.security.ssl.transport.enabled
          value: "true"
        - name: cluster.routing.allocation.disk.watermark.low
          value: "5gb"
        - name: cluster.routing.allocation.disk.watermark.high
          value: "3gb"
        - name: cluster.routing.allocation.disk.watermark.flood_stage
          value: "2gb"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        - name: http.port
          value: "9201"
        ports:
        - containerPort: 9201
        resources:
          limits:
            memory: 8Gi
        volumeMounts:
        - name: osdata
          mountPath: /usr/share/opensearch/data
        readinessProbe:
          exec:
            command:
            - curl
            - http://localhost:9201
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: osdata
        persistentVolumeClaim:
          claimName: osdata01
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch01
  namespace: ragflow
spec:
  selector:
    app: opensearch
  ports:
    - protocol: TCP
      port: 9201
      targetPort: 9201
      nodePort: 31201
  type: NodePort
---
# ======================
# Infinity Service
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinity
  namespace: ragflow
  labels:
    app: infinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinity
  template:
    metadata:
      labels:
        app: infinity
    spec:
      containers:
      - name: infinity
        image: infiniflow/infinity:v0.6.0-dev3
        command: ["/app/infinity", "-f", "/etc/infinity/infinity_conf.toml"]
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        ports:
        - containerPort: 23817
        - containerPort: 23820
        - containerPort: 5432
        resources:
          limits:
            memory: 8Gi
        volumeMounts:
        - name: infinity-data
          mountPath: /var/infinity
        - name: infinity-config
          mountPath: /etc/infinity
        readinessProbe:
          exec:
            command:
            - curl
            - http://localhost:23820/admin/node/current
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: infinity-data
        persistentVolumeClaim:
          claimName: infinity-data
      - name: infinity-config
        configMap:
          name: ragflow-config
          items:
          - key: infinity_conf.toml
            path: infinity_conf.toml
---
apiVersion: v1
kind: Service
metadata:
  name: infinity
  namespace: ragflow
spec:
  selector:
    app: infinity
  ports:
    - name: thrift
      protocol: TCP
      port: 23817
      targetPort: 23817
    - name: http
      protocol: TCP
      port: 23820
      targetPort: 23820
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
# ======================
# Sandbox Executor
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-executor-manager
  namespace: ragflow
  labels:
    app: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
      - name: sandbox-executor-manager
        image: infiniflow/sandbox-executor-manager:latest
        securityContext:
          privileged: true
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        - name: SANDBOX_EXECUTOR_MANAGER_POOL_SIZE
          value: "3"
        - name: SANDBOX_BASE_PYTHON_IMAGE
          value: "infiniflow/sandbox-base-python:latest"
        - name: SANDBOX_BASE_NODEJS_IMAGE
          value: "infiniflow/sandbox-base-nodejs:latest"
        - name: SANDBOX_ENABLE_SECCOMP
          value: "false"
        - name: SANDBOX_MAX_MEMORY
          value: "256m"
        - name: SANDBOX_TIMEOUT
          value: "10s"
        ports:
        - containerPort: 9385
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        readinessProbe:
          exec:
            command:
            - curl
            - http://localhost:9385/healthz
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-executor-manager
  namespace: ragflow
spec:
  selector:
    app: sandbox
  ports:
    - protocol: TCP
      port: 9385
      targetPort: 9385
  type: ClusterIP
---
# ======================
# MySQL Service
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ragflow
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.39
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ragflow-secrets
              key: MYSQL_PASSWORD
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        command:
        - mysqld
        - --max_connections=1000
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --default-authentication-plugin=mysql_native_password
        - --tls_version=TLSv1.2,TLSv1.3
        - --init-file=/docker-entrypoint-initdb.d/init.sql
        - --binlog_expire_logs_seconds=604800
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - "-uroot"
            - "-p$(MYSQL_ROOT_PASSWORD)"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: init-script
        configMap:
          name: ragflow-config
          items:
          - key: init.sql
            path: init.sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ragflow
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 33066
  type: NodePort
---
# ======================
# MinIO Service
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: ragflow
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
        command:
        - /bin/sh
        - -c
        - minio server --console-address ":9001" /data
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: ragflow-secrets
              key: MINIO_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ragflow-secrets
              key: MINIO_PASSWORD
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: ragflow-config
              key: TIMEZONE
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-data
          mountPath: /data
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:9000/minio/health/live
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ragflow
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
---
# ======================
# Redis (Valkey) Service
# ======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ragflow
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: valkey/valkey:8
        command:
        - redis-server
        - "--requirepass"
        - "$(REDIS_PASSWORD)"
        - "--maxmemory"
        - "128mb"
        - "--maxmemory-policy"
        - "allkeys-lru"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ragflow-secrets
              key: REDIS_PASSWORD
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        readinessProbe:
          exec:
            command:
            - redis-cli
            - "-a"
            - "$(REDIS_PASSWORD)"
            - "ping"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ragflow
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP