apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  # 非敏感环境变量
  node.name: "opensearch01"
  bootstrap.memory_lock: "false"
  discovery.type: "single-node"
  plugins.security.disabled: "false"
  plugins.security.ssl.http.enabled: "false"
  plugins.security.ssl.transport.enabled: "true"
  cluster.routing.allocation.disk.watermark.low: "5gb"
  cluster.routing.allocation.disk.watermark.high: "3gb"
  cluster.routing.allocation.disk.watermark.flood_stage: "2gb"
  http.port: "9201"
  TZ: "Asia/Shanghai"  # 从 .env 中的 TIMEZONE
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secret
type: Opaque
stringData:
  # 敏感环境变量（实际使用时应替换为实际值）
  OPENSEARCH_PASSWORD: "infini_rag_flow_OS_01"  # 从 .env 获取
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "infini_rag_flow_OS_01"  # 从 .env 获取
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osdata01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # 根据实际需求调整大小
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragflow-opensearch-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: hub.icert.top/opensearchproject/opensearch:2.19.1
        ports:
        - containerPort: 9201
        env:
          # 从 ConfigMap 注入非敏感变量
          - name: OPENSEARCH_USER
            value: "admin"
          - name: node.name
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: node.name
          - name: bootstrap.memory_lock
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: bootstrap.memory_lock
          - name: discovery.type
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: discovery.type
          - name: plugins.security.disabled
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: plugins.security.disabled
          - name: plugins.security.ssl.http.enabled
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: plugins.security.ssl.http.enabled
          - name: plugins.security.ssl.transport.enabled
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: plugins.security.ssl.transport.enabled
          - name: cluster.routing.allocation.disk.watermark.low
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: cluster.routing.allocation.disk.watermark.low
          - name: cluster.routing.allocation.disk.watermark.high
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: cluster.routing.allocation.disk.watermark.high
          - name: cluster.routing.allocation.disk.watermark.flood_stage
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: cluster.routing.allocation.disk.watermark.flood_stage
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: TZ
          - name: http.port
            valueFrom:
              configMapKeyRef:
                name: opensearch-config
                key: http.port
          # 从 Secret 注入敏感变量
          - name: OPENSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opensearch-secret
                key: OPENSEARCH_PASSWORD
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opensearch-secret
                key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        resources:
          limits:
            cpu: "2"
            memory: "8Gi"  # 从 .env 的 MEM_LIMIT
          requests:
            cpu: "0.5"
            memory: "4Gi"
        livenessProbe:
          exec:  
            command:
              - "sh"
              - "-c"
              - "curl -s -k -u admin:$OPENSEARCH_PASSWORD http://localhost:9201"
          initialDelaySeconds: 100
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - curl
            - -k
            - http://localhost:9201
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          privileged: false
          capabilities:
            add: ["IPC_LOCK"]
      volumes:
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: osdata01
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
spec:
  type: NodePort
  selector:
    app: opensearch
  ports:
    - protocol: TCP
      port: 9201
      targetPort: 9201
      nodePort: 31202  # 外部访问端口（范围 30000-32767）