apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS rag_flow;
    USE rag_flow;
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
stringData:
  MYSQL_PASSWORD: "infini_rag_flow"  # 从 .env 文件中获取的实际值
  TIMEZONE: "Asia/Shanghai"          # 从 .env 文件中获取的实际值
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # 根据实际需求调整存储大小
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragflow-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragflow-mysql
  template:
    metadata:
      labels:
        app: ragflow-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.39
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: TZ
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: TIMEZONE
        command:
        - mysqld
        - "--max_connections=1000"
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
        - "--default-authentication-plugin=mysql_native_password"
        - "--tls_version=TLSv1.2,TLSv1.3"
        #- "--init-file=/docker-entrypoint-initdb.d/init.sql"
        - "--binlog_expire_logs_seconds=604800"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - "-uroot"
            - "-p$(MYSQL_ROOT_PASSWORD)"
          initialDelaySeconds: 100
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 120
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - "-uroot"
            - "-p$(MYSQL_ROOT_PASSWORD)"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
            limits:
              cpu: "2"
              memory: "8Gi"  # 从 .env 的 MEM_LIMIT
            requests:
              cpu: "0.5"
              memory: "4Gi"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
      - name: init-script
        configMap:
          name: mysql-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: ragflow-mysql-service
spec:
  selector:
    app: ragflow-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30005  # 可选：NodePort 范围 30000-32767
  type: NodePort       # 根据需求可改为 LoadBalancer 或 ClusterIP